name: PR

on: [pull_request, pull_request_review]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello 123 ${{ secrets.SECRET }}"
    - run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git fetch origin
        git checkout main
        git pull
        echo ${{github.sha}} >> ${{github.sha}}.txt
        git add .
        git commit -am "${{github.sha}}"
        git push
      continue-on-error: true
      id: git
    - run: |
        exit 1
      if: steps.git.outcome != 'failure'
    - run: echo "all good."